### ISSUE TITLE
EXC_BAD_ACCESS when using dominantColors() with default arguments

### ISSUE THREAD

**Issue by wiencheck** [Boris-Em/ColorKit#21]
When trying to fetch dominant colors from some images an exception is raised.

![Screen Shot 2022-04-21 at 09 57 23](https://user-images.githubusercontent.com/25985996/164407609-6732c5c8-d73e-4471-892e-aaf1f91909c7.png)

File: `DominantColors.swift` line `159`

This is the image that's causing crash
![IMG_3836](https://user-images.githubusercontent.com/25985996/164407771-cbec02a2-7dc4-49ce-980b-a1f1b86d6d17.jpeg)

In my code I just called the `dominantColors()` method with default arguments.

**Comment by wiencheck** [comment]
@sgousseau Fixed in #22

**Comment by danilsmakotin** [comment]
Hi @wiencheck. I still get a crash in master branch. This is sample of code for previously mentioned image:

``` 
let url = URL(string: "https://user-images.githubusercontent.com/25985996/164407771-cbec02a2-7dc4-49ce-980b-a1f1b86d6d17.jpeg")!
let (data, _) = try await URLSession.shared.data(from: url)
let colors = try UIImage(data: data)!.dominantColors(with: .high)
```

There is no crash for `.low` and `.fair` qualities. Only for `.high` and `.best`.
